name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.4-1.3.0-quilt-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5d896daa9c8bc45614b0f76b6260ced0498c0af3f2f96acd9f32de211a0b1f0"

[versions]
minecraft = "1.21.4"
quilt = "0.28.0-beta.3"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
