name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.4-1.3.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38849570bdc8e3ee557d0676a5dcb7764c06c1333f61465721b10eaeb65fa655"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
