name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.3-1.3.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f00f3b7aaa2c319a66e26f8e862cb62b89eadb546e2d927da32f77914d52fd81"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
