name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.4-1.3.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ae064b09eaed2189dac76f3c6398d48eda3101e87dcf069f444cab1b928af6b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
