name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.3-1.3.0-quilt-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b56a907ec655b11f4153d085ee963b73bce2a22a6a787455c729d37a28de642"

[versions]
minecraft = "1.21.3"
quilt = "0.27.0-beta.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
