name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.3-1.3.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e66b2504ecc8befb43442d4ca275f0136e1d644c2a00bda282a6cda5097969"

[versions]
fabric = "0.16.8"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
