name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.3-1.3.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d96ecdc6624d42616cb2011559ce0402a8c2989a28f6fbe77aa3b7996bbff79"

[versions]
fabric = "0.16.8"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
