name = "Turtle's Optimize Modpack"
author = "Aturtle6813"
version = "mc1.21.1*1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e145ec899156f60b72362497688a8dc67b6e9ec721ae9c72613556409103374"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
