name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.1-1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67d7e886876e2056dd897460fd293c949b16ba7f41f9ff43d3d0b3d55aefc3a6"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
