name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.4-1.3.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27de2f31bf8133b99eb9f29f33ce78512a83d887199451dc1f02a226b1abac5e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
