name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.3-1.3.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e15a56dd02b3b8d64fced3e65cf7c40ef6309a218c6376a491a6742827f4c7e9"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
