name = "Turtle's Server Modpack"
author = "Aturtle6813"
version = "mc1.21.1-1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38ce72431ac776914782135b814bf1ea1fe7380cadaff32951338354a3e51fcb"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.x"]
