name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.3-1.3.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f37a60487fcb169c91d7f670d039a7c3a44154093fead76b4e238358db481c54"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = ["1.21.2"]
