name = "Turtle's Auxiliar Modpack"
author = "Aturtle6813"
version = "mc1.21.4-1.3.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36f1038282deb6858e52a9835452eef07065ade34bb7a944bbb1d8e59e634497"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
